function(praxis_target_warnings target)
    get_target_property(_type ${target} TYPE)
    if(MSVC)
        if(_type STREQUAL "INTERFACE_LIBRARY")
            target_compile_options(${target} INTERFACE /W4 /permissive-)
        else()
            target_compile_options(${target} PRIVATE /W4 /permissive-)
        endif()
    else()
        if(_type STREQUAL "INTERFACE_LIBRARY")
            target_compile_options(${target} INTERFACE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
        else()
            target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
        endif()
    endif()
endfunction()
